# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  group: 'Security'

pool:
  name: 'Default'

steps:

- task: CmdLine@2
  inputs:
    script: |
      curl --request GET --url "https://erasoxavier.atlassian.net/rest/api/3/issue/SCRUM-1/comment" --user "eraso.xavier@gmail.com:$(jiraToken)" --header "Accept: application/json"
    failOnStderr: true

