trigger:
  branches:
    include:
      - master

variables:
  - group: 'test-group'
  - name: cesAuth  # Ensure cesAuth is defined in your pipeline variables/secrets
    value: 'your_cesAuth_value_here'
  - name: jiraToken  # Ensure jiraToken is defined in your pipeline variables/secrets
    value: 'your_jira_token_here'

pool:
  name: 'Default'

steps:

- task: PowerShell@2
  displayName: Create Assignment
  inputs:
    targetType: 'inline'
    script: |
      # Define headers
      $headers = @{
        "Authorization" = "$(cesAuth)"
        "Content-Type" = "application/json"
      }

      # Define body for assignment creation
      $body = @{
        "stream" = "GITDEMO"
        "application" = "GIT1"
        "subAppl" = "GIT1"
        "defaultPath" = "WRK2"
        "description" = "assignment for SCRUM-1"
        "assignmentPrefix" = "GIT1"
      } | ConvertTo-Json

      # Log headers and body for debugging
      Write-Host "Headers: $($headers | ConvertTo-Json)"
      Write-Host "Body: $body"

      try {
        $response = Invoke-WebRequest -Uri "http://cwcc.bmc.com:2020/ispw/iccga/assignments/" -Method POST -Headers $headers -Body $body -ContentType "application/json"
        Write-Host "Assignment Creation Response: $($response.Content)"
      }
      catch {
        Write-Host "Error creating assignment: $($_.Exception.Message)"
        if ($_.Exception.Response -ne $null) {
          $responseStream = [System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())
          $responseBody = $responseStream.ReadToEnd()
          Write-Host "Response Body: $responseBody"
        }
        exit 1
      }
    
- task: PowerShell@2
  displayName: 'Jira Post Comment'
  inputs:
    targetType: 'inline'
    script: |
      # Define headers for Jira API
      $headers = @{
          "Accept" = "application/json"
      }

      # Encode credentials for Basic Authentication
      $username = "eraso.xavier@gmail.com"
      $jiraToken = "$(jiraToken)"
      $credentials = "$($username):$($jiraToken)"
      $bytes = [System.Text.Encoding]::UTF8.GetBytes($credentials)
      $encodedCredentials = [Convert]::ToBase64String($bytes)
      $headers["Authorization"] = "Basic $encodedCredentials"

      # Example response body for demonstration
      $responseBody = @{
          Response = @{
              assignmentId = "ASSIGNMENT_ID_VALUE"
          }
      }

      # Construct the body for posting a comment to Jira issue
      $jiraBody = @{
          body = @{
              content = @(
                  @{
                      content = @(
                          @{
                              text = "$($responseBody.Response.assignmentId)"
                              type = "text"
                          }
                      )
                      type = "paragraph"
                  }
              )
              type = "doc"
              version = 1
          }
      } | ConvertTo-Json

      # Define the URL for Jira REST API endpoint (replace SCRUM-1 with actual issue key)
      $jiraUrl = "https://erasoxavier.atlassian.net/rest/api/2/issue/SCRUM-1/comment"

      # Invoke the POST request to post comment in Jira
      try {
        $jiraResponse = Invoke-WebRequest -Uri $jiraUrl -Method Post -Headers $headers -Body $jiraBody -ContentType "application/json"
        Write-Host "Jira Comment Response: $($jiraResponse.Content)"
      }
      catch {
        Write-Host "Error posting comment to Jira: $($_.Exception.Message)"
        if ($_.Exception.Response -ne $null) {
          $responseStream = [System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())
          $responseBody = $responseStream.ReadToEnd()
          Write-Host "Response Body: $responseBody"
        }
        exit 1
      }


- task: PowerShell@2
  displayName: Jira Get Comment
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
        "Accept" = "application/json"
      }
      $credentials = "eraso.xavier@gmail.com:$(jiraToken)"
      $Bytes = [System.Text.Encoding]::UTF8.GetBytes($credentials)
      $encodedCredentials = [Convert]::ToBase64String($Bytes)
      $headers["Authorization"] = "Basic $encodedCredentials"
      $response = Invoke-WebRequest -Uri "https://erasoxavier.atlassian.net/rest/api/2/issue/SCRUM-1/comment" -Method GET -Headers $headers

      # Convert the response content to a JSON object
      $parsedJson = $response.Content | ConvertFrom-Json

      # Access the 'body' field of the first comment in the 'comments' array
      $text = $parsedJson.comments[0].body

      Write-Host "Affichage :"
      # Write-Host $response removed to avoid cluttering the output with raw HTML/JSON
      Write-Host $text
