trigger:
- master

variables:
- group: 'test-group'

pool:
  name: 'Default'

steps:

- task: PowerShell@2
  displayName: Check Release
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{}
          $headers.Add("Authorization", "$(cesAuth)")
          $headers.Add("Content-Type", "application/json")
      Invoke-WebRequest -Uri "http://cwcc.bmc.com:2020/ispw/iccga/releases/BMCTEST" -Method GET -Headers $headers

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
        "Authorization" = "$(cesAuth)"
        "Content-Type" = "application/json"
      }

      $body = @{
        "stream" = "GITFLOW"
        "application" = "GFLD"
        "subAppl" = "GFLD"
        "defaultPath" = "FEAT"
        "description" = "assignment for SCRUM-1"
        "assignmentPrefix" = "feature/"
      } | ConvertTo-Json

      # Log headers and body
      Write-Host "Headers: $($headers | ConvertTo-Json)"
      Write-Host "Body: $body"

      try {
        $response = Invoke-WebRequest -Uri "http://cwcc.bmc.com:2020/ispw/ic2ga/assignments/" -Method POST -Headers $headers -Body $body -ContentType "application/json"
        Write-Host "Response: $($response.Content)"
      }
      catch {
        Write-Host "Error: $($_.Exception.Message)"
        if ($_.Exception.Response -ne $null) {
          $responseStream = [System.IO.StreamReader]::new($_.Exception.Response.GetResponseStream())
          $responseBody = $responseStream.ReadToEnd()
          Write-Host "Response Body: $responseBody"
        }
        exit 1
      }

- task: PowerShell@2
  displayName: Jira Comment
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
        "Accept" = "application/json"
      }
      $credentials = "eraso.xavier@gmail.com:$(jiraToken)"
      $Bytes = [System.Text.Encoding]::UTF8.GetBytes($credentials)
      $encodedCredentials = [Convert]::ToBase64String($Bytes)
      $headers["Authorization"] = "Basic $encodedCredentials"
      $response = Invoke-WebRequest -Uri "https://erasoxavier.atlassian.net/rest/api/2/issue/SCRUM-1/comment" -Method GET -Headers $headers

      # Convert the response content to a JSON object
      $parsedJson = $response.Content | ConvertFrom-Json

      # Access the 'body' field of the first comment in the 'comments' array
      $text = $parsedJson.comments[0].body

      Write-Host "Affichage :"
      # Write-Host $response removed to avoid cluttering the output with raw HTML/JSON
      Write-Host $text
    
    