# Starter pipeline

trigger:
- master

variables:
  group: 'Security'

pool:
  name: 'Default'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
        "Accept" = "application/json"
      }
      $credentials = "eraso.xavier@gmail.com:$(JiraToken)"
      $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credentials))
      $headers["Authorization"] = "Basic $encodedCredentials"
      Invoke-WebRequest -Uri "https://erasoxavier.atlassian.net/rest/api/3/issue/SCRUM-1/comment" -Method GET -Headers $headers
  env:
    JiraToken: $(jiraToken)
