# Starter pipeline

trigger:
- master

variables:
  group: 'Security'

pool:
  name: 'Default'


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      curl --request GET --url "https://erasoxavier.atlassian.net/rest/api/3/issue/SCRUM-1/comment" --user "eraso.xavier@gmail.com:$($env:JIRA_TOKEN)" --header "Accept: application/json"
  env:
    JIRA_TOKEN: $(jiraToken)
