trigger:
- master

variables:
  group: 'Security'

pool:
  name: 'Default'

steps:
- task: PowerShell@2
  displayName: Check Release
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{}
          $headers.Add("Authorization", '"$(connectionId)"')
          $headers.Add("Content-Type", "application/json")
      Invoke-WebRequest -Uri "http://cwcc.bmc.com:2020/ispw/iccga/releases/BMCTEST'" -Method GET -Headers $headers

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
        "Accept" = "application/json"
      }
      $credentials = "eraso.xavier@gmail.com:$env:jiraToken"
      $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credentials))
      $headers["Authorization"] = "Basic $encodedCredentials"
      echo $headers
      Invoke-WebRequest -Uri "https://erasoxavier.atlassian.net/rest/api/3/issue/SCRUM-1/comment" -Method GET -Headers $headers
  env:
    jiraToken: $(jiraToken)
