trigger:
- master

variables:
- group: 'test-group'

pool:
  name: 'Default'

steps:

- task: PowerShell@2
  displayName: Check Release
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{}
          $headers.Add("Authorization", $(cesAuth))
          $headers.Add("Content-Type", "application/json")
      echo $headers
      Invoke-WebRequest -Uri "http://cwcc.bmc.com:2020/ispw/iccga/releases/BMCTEST'" -Method GET -Headers $headers
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo $JIRA_TOKEN
      $headers = @{
        "Accept" = "application/json"
      }
      $credentials = "eraso.xavier@gmail.com:$JIRA_TOKEN"
      echo $credentials
      $encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credentials))
      $headers["Authorization"] = "Basic $encodedCredentials"
      echo $headers
      Invoke-WebRequest -Uri "https://erasoxavier.atlassian.net/rest/api/3/issue/SCRUM-1/comment" -Method GET -Headers $headers
  env:
    JIRA_TOKEN: $(jiraToken)
