trigger:
- master

variables:
- group: 'test-group'

pool:
  name: 'Default'

steps:

- task: PowerShell@2
  displayName: Check Release
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{}
          $headers.Add("Authorization", "$(cesAuth)")
          $headers.Add("Content-Type", "application/json")
      Invoke-WebRequest -Uri "http://cwcc.bmc.com:2020/ispw/iccga/releases/BMCTEST" -Method GET -Headers $headers
  
- task: PowerShell@2
  displayName: Jira Comment
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{
        "Accept" = "application/json"
      }
      $credentials = "eraso.xavier@gmail.com:$(jiraToken)"
      $Bytes = [System.Text.Encoding]::UTF8.GetBytes($credentials)
      $encodedCredentials = [Convert]::ToBase64String($Bytes)
      $headers["Authorization"] = "Basic $encodedCredentials"
      $response = Invoke-WebRequest -Uri "https://erasoxavier.atlassian.net/rest/api/2/issue/SCRUM-1" -Method GET -Headers $headers
      Write-Host "Full JSON Response:"
      Write-Host $parsedJson | ConvertTo-Json -Depth 100

      # Assuming the correct path to the name property is found to be in someObject.name
      # Adjust the following line according to the actual structure
      $text = $parsedJson.fields.summary # Example adjustment based on common JIRA API structure

      Write-Host "Affichage :"
      Write-Host $response
      Write-Host $text
    
